### ISSUE TITLE
App immediately crashes on launch

### ISSUE THREAD

**Issue by iqfareez** [mptwaktusolat/app_waktu_solat_malaysia#228]
A user leave a review on Google Play:

![image](https://github.com/mptwaktusolat/app_waktu_solat_malaysia/assets/60868965/7a1aeb83-699f-43b4-ad58-12973b242412)

Fortunately, I can reproduce the issue. This issue only occurs on **Android 14** or greater.

1. Install the app. You can grab the release [here](https://github.com/mptwaktusolat/app_waktu_solat_malaysia/releases/tag/2.12.1%2B145)
2. Launch the app
3. When it comes to the notification page on the onboarding screen. It will ask the permission to allow alarm & reminders.
![Screenshot_1708045038](https://github.com/mptwaktusolat/app_waktu_solat_malaysia/assets/60868965/304baa30-4d7e-4c3d-9a8f-358b9558abca)
4. Don't give permission. Just press back button.
5. Continue the onboarding.
6. Go to homescreen, add a new prayer time widget.
![Screenshot_1708045578](https://github.com/mptwaktusolat/app_waktu_solat_malaysia/assets/60868965/913221b8-f97a-4831-b95c-e03361dd5038)
7. Open the app. After few moments, it will crash.

## Error log

```shell
adb shell
logcat | grep live.iqfareez.waktu
```

```shell
02-16 00:49:07.567 18296 18296 E AndroidRuntime: Process: live.iqfareez.waktusolatmalaysia, PID: 18296
02-16 00:49:07.567 18296 18296 E AndroidRuntime: java.lang.RuntimeException: Unable to start receiver live.iqfareez.waktusolatmalaysia.SolatHorizontalWidget: java.lang.SecurityException: Caller live.iqfareez.waktusolatmalaysia needs to hold android.permission.SCHEDULE_EXACT_ALARM or android.permission.USE_EXACT_ALARM to set exact alarms.
02-16 00:49:07.567 18296 18296 E AndroidRuntime: Caused by: java.lang.SecurityException: Caller live.iqfareez.waktusolatmalaysia needs to hold android.permission.SCHEDULE_EXACT_ALARM or android.permission.USE_EXACT_ALARM to set exact alarms.
02-16 00:49:07.567 18296 18296 E AndroidRuntime:        at live.iqfareez.waktusolatmalaysia.SolatHorizontalWidgetKt.scheduleNextUpdate(SolatHorizontalWidget.kt:211)
02-16 00:49:07.567 18296 18296 E AndroidRuntime:        at live.iqfareez.waktusolatmalaysia.SolatHorizontalWidgetKt.access$scheduleNextUpdate(SolatHorizontalWidget.kt:1)
02-16 00:49:07.567 18296 18296 E AndroidRuntime:        at live.iqfareez.waktusolatmalaysia.SolatHorizontalWidget.onUpdate(SolatHorizontalWidget.kt:45)
02-16 00:49:07.567 18296 18296 E AndroidRuntime:        at live.iqfareez.waktusolatmalaysia.SolatHorizontalWidget.onReceive(SolatHorizontalWidget.kt:57)
02-16 00:49:10.432   555  1531 W ActivityTaskManager:   Force finishing activity live.iqfareez.waktusolatmalaysia/.MainActivity
02-16 00:49:10.697   555  1551 I ActivityManager: Process live.iqfareez.waktusolatmalaysia (pid 18296) has died: fg  TOP
```

**Comment by iqfareez** [comment]
References:
- https://developer.android.com/reference/android/app/AlarmManager.html#canScheduleExactAlarms()
- https://developer.android.com/reference/android/app/AlarmManager#setExact(int,%20long,%20android.app.PendingIntent)
- https://developer.android.com/reference/android/app/AlarmManager#set(int,%20long,%20android.app.PendingIntent)

**Comment by iqfareez** [comment]
Fixed on latest release https://waktusolat.app/en/changelog#2.12.2
